// Write a javascript program to pretend to look like a hacker. Write an async function which will simply display the following output
// Initializing hack program ....
// Hacking hunain username...
// Username found hunain15...
// Connecting to facebook...
// Try to use HTML & styling if possible 